package com.brent.demo.mode.po;

import java.util.Date;

public class NameDemo {
    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column name_demo.id
     *
     * @mbg.generated Thu Dec 31 11:15:18 CST 2020
     */
    private Integer id;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column name_demo.c_name
     *
     * @mbg.generated Thu Dec 31 11:15:18 CST 2020
     */
    private String cName;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column name_demo.age
     *
     * @mbg.generated Thu Dec 31 11:15:18 CST 2020
     */
    private Integer age;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column name_demo.create_time
     *
     * @mbg.generated Thu Dec 31 11:15:18 CST 2020
     */
    private Date createTime;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column name_demo.telephone
     *
     * @mbg.generated Thu Dec 31 11:15:18 CST 2020
     */
    private String telephone;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column name_demo.id
     *
     * @return the value of name_demo.id
     *
     * @mbg.generated Thu Dec 31 11:15:18 CST 2020
     */
    public Integer getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column name_demo.id
     *
     * @param id the value for name_demo.id
     *
     * @mbg.generated Thu Dec 31 11:15:18 CST 2020
     */
    public void setId(Integer id) {
        this.id = id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column name_demo.c_name
     *
     * @return the value of name_demo.c_name
     *
     * @mbg.generated Thu Dec 31 11:15:18 CST 2020
     */
    public String getcName() {
        return cName;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column name_demo.c_name
     *
     * @param cName the value for name_demo.c_name
     *
     * @mbg.generated Thu Dec 31 11:15:18 CST 2020
     */
    public void setcName(String cName) {
        this.cName = cName == null ? null : cName.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column name_demo.age
     *
     * @return the value of name_demo.age
     *
     * @mbg.generated Thu Dec 31 11:15:18 CST 2020
     */
    public Integer getAge() {
        return age;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column name_demo.age
     *
     * @param age the value for name_demo.age
     *
     * @mbg.generated Thu Dec 31 11:15:18 CST 2020
     */
    public void setAge(Integer age) {
        this.age = age;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column name_demo.create_time
     *
     * @return the value of name_demo.create_time
     *
     * @mbg.generated Thu Dec 31 11:15:18 CST 2020
     */
    public Date getCreateTime() {
        return createTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column name_demo.create_time
     *
     * @param createTime the value for name_demo.create_time
     *
     * @mbg.generated Thu Dec 31 11:15:18 CST 2020
     */
    public void setCreateTime(Date createTime) {
        this.createTime = createTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column name_demo.telephone
     *
     * @return the value of name_demo.telephone
     *
     * @mbg.generated Thu Dec 31 11:15:18 CST 2020
     */
    public String getTelephone() {
        return telephone;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column name_demo.telephone
     *
     * @param telephone the value for name_demo.telephone
     *
     * @mbg.generated Thu Dec 31 11:15:18 CST 2020
     */
    public void setTelephone(String telephone) {
        this.telephone = telephone == null ? null : telephone.trim();
    }
}