package com.brent.demo.mode.po;

import lombok.Data;

import java.util.Date;

/**
 *
 * This class was generated by MyBatis Generator.
 * This class corresponds to the database table name_demo
 */
@Data
public class NameDemo {
    /**
     *   主键
     *
     * column: name_demo.id
     */
    private Integer id;

    /**
     *   姓名
     *
     * column: name_demo.c_name
     */
    private String cName;

    /**
     *   年龄
     *
     * column: name_demo.age
     */
    private Integer age;

    /**
     *   时间
     *
     * column: name_demo.create_time
     */
    private Date createTime;

    /**
     *   电话
     *
     * column: name_demo.telephone
     */
    private String telephone;

    /**
     *   状态
     *
     * column: name_demo.c_state
     */
    private Integer cState;
}